CREATE DATABASE IF NOT EXISTS ikomers_db;
USE ikomers_db;

CREATE TABLE IF NOT EXISTS users (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(50) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO users (username, password)
VALUES ('demo', '$2y$10$H4LRuYh8zV6HnSgG0mOwzOdSHbWKV3GRj81K.T3fAukL1NhvFJ9tm')
ON DUPLICATE KEY UPDATE username = VALUES(username);
